---
# Workload tasks

- name: Log cluster provisioning success
  ansible.builtin.debug:
    msg: |
      TALM event received at {{ ansible_date_time.iso8601 }}:
      Cluster {{ item.cguName }} managed by {{ item.leafHubName }} hub SUCCEEDED.
      Cluster is ready for workloads.

- name: "Create maintenance label for cluster {{ item.cguName }}"
  k8s:
    kubeconfig: "{{ kubeconfig }}"
    state: patched
    api_version: cluster.open-cluster-management.io/v1
    kind: ManagedCluster
    name: "{{ item.cguName }}"
    definition:
      metadata:
        labels:
          ztp-ansible: "running"

# Download the SNO kubeconfig
# Create a namespace on the SNO

- name: Pause for 1 minute
  ansible.builtin.pause:
    seconds: 60

- name: "Create completed label for cluster {{ item.cguName }}"
  k8s:
    kubeconfig: "{{ kubeconfig }}"
    state: patched
    api_version: cluster.open-cluster-management.io/v1
    kind: ManagedCluster
    name: "{{ item.cguName }}"
    definition:
      metadata:
        labels:
          ztp-ansible: "completed"
