---
# Test rulebook for AAP with EDA to read TALM events from MCGH Kafka

- name: Read messages from a kafka topic from MCGH
  hosts: all
  execution_strategy: parallel
  sources:
  - ansible.eda.kafka:
      host: "{{ HOST }}"
      port: 443
      topic: "{{ TOPIC }}"
      check_hostname: false
      cafile: "{{ eda.filename.ca_cert }}"
      certfile: "{{ eda.filename.client_cert }}"
      keyfile: "{{ eda.filename.client_key }}"
      verify_mode: CERT_NONE
  rules:
  - name: Run job template on CguSuccess events
    condition: event.body is selectattr('reason', 'match', 'CguSuccess') and event.body is selectattr('reportingController', 'match', 'ClusterGroupUpgrade')
    actions:
    - run_job_template:
        name: "ztp-day2-aap-controller-job-template"
        organization: Default
    - print_event:
        pretty: true
