---
# Test playbook for ZTP Day 2 Automation

- name: "Test ZTP day2 playbook (split play)"
  hosts: localhost
  connection: local
  tasks:

  # - ansible.builtin.debug:
  #     msg: "Host Variables: {{ hostvars[{{ inventory_hostname }}] }}"
  # - ansible.builtin.debug:
  #     msg: "Number of body elements: {{ ansible_eda.event.body | length }}"
  #   when: ansible_eda is defined
  # - ansible.builtin.debug:
  #     msg: "ansible_eda.event.body: {{ item }}"
  #   when: ansible_eda is defined
  #   loop: "{{ ansible_eda.event.body }}"

  - name: Process CguSuccess TALM events for Cluster ZTP day2 automation
    ansible.builtin.add_host:
      name: "{{ item.cguName }}"
      groups: target_clusters
      ansible_host: localhost
      leafHubName: "{{ item.leafHubName }}"
    loop: "{{ ansible_eda.event.body }}"
    loop_control:
      label: "{{ item.cguName | default('invalid-event') }}"
    when:
    - item.eventAnnotations is defined
    - item.reason == "CguSuccess"
    - "{{ 'cgu.openshift.io/event-type' in item.eventAnnotations }}"
    - item.eventAnnotations['cgu.openshift.io/event-type'] == "cluster"
    - "{{ 'cgu.openshift.io/cluster-name' in item.eventAnnotations }}"
    - item.eventAnnotations['cgu.openshift.io/cluster-name'] is defined
    - item.eventAnnotations['cgu.openshift.io/cluster-name'] == item.cguName
    - item.eventNamespace == "ztp-install"

- name: Apply tasks per cluster
  hosts: target_clusters
  connection: local
  tasks:
  - name: Obtain kubeconfig and apply day2 tasks
    ansible.builtin.include_tasks: tasks/day2-tasks-concurrent.yml
    vars:
      kubeconfig_output_path: "/tmp/{{ inventory_hostname }}-kubeconfig"
